# MCP Base64 Server Production Configuration
# This file contains production-optimized settings

server:
  name: "mcp-base64-server"
  version: "1.0.0"
  description: "MCP server providing base64 encoding and decoding tools"

# Transport configuration for production
transport:
  # Use HTTP transport for production deployments
  type: "http"
  
  # HTTP transport settings
  http:
    host: "0.0.0.0"  # Listen on all interfaces
    port: 3000
    
# Standalone HTTP API server settings
http_server:
  enabled: true
  host: "0.0.0.0"  # Listen on all interfaces
  port: 8080
  
# Production logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  use_structured_format: true
  log_file_path: "logs/mcp-base64-server.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  use_colors: false  # Disable colors in production logs
  
# Debug disabled in production
debug:
  enabled: false
  inspector_port: 9000

# Performance settings
performance:
  max_workers: 4
  worker_timeout: 30
  keep_alive: 2
  max_request_size: 1048576  # 1MB

# Security settings
security:
  cors_origins: ["*"]  # Configure specific origins in production
  max_content_length: 1048576  # 1MB
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    
# Monitoring settings
monitoring:
  enabled: true
  metrics_port: 9100
  health_check_interval: 30